apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    tier: db
    app: postgres-Deployment
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    tier: db-postgres