apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379