apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
   app: vote-deployment
spec:
  template:
    metadata:
      name: vote-pod
      labels:
        app: vote
    spec:
      containers:
      - name: vote-containers
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
          name: vote
  replicas: 2
  selector:
    matchLabels:
      app: vote