apiVersion: v1
kind: Service
metdata:
  name: vote-Service
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - name: "vote-service"
    port: 8080
    targetPort: 80
    NodePort: 30001